on: push
name: Deploying
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: mattiasgeniar/php73

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install composer dependencies
      run: composer install --no-suggest --no-progress --no-interaction
    - name: Run PHPUnit
      run: php vendor/bin/phpunit -c phpunit.xml
  deploy:
    needs: phpunit
    runs-on: ubuntu-latest
    container:
      image: misterio92/ci-php-node:2.0

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install composer dependencies
      run: composer install --no-suggest --no-progress --no-interaction --no-dev
    - name: Prepare deployment
      run: |
        apt-get update -yq && apt-get install openssh-client -y
        eval $(ssh-agent -s)
        ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY }}")
        '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - name: Deploy
      run: rsync -av -e "ssh" --exclude="public/uploads" public recipes src views composer.json p201628@p201628.mittwald.info:/html/rezepte
